# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  NutzLib_config = debug
  Sandbox_config = debug

else ifeq ($(config),release)
  NutzLib_config = release
  Sandbox_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := NutzLib Sandbox

.PHONY: all clean help $(PROJECTS) Core Tools

all: $(PROJECTS)

Core: NutzLib

Tools: Sandbox

NutzLib:
ifneq (,$(NutzLib_config))
	@echo "==== Building NutzLib ($(NutzLib_config)) ===="
	@${MAKE} --no-print-directory -C NutzLib -f Makefile config=$(NutzLib_config)
endif

Sandbox: NutzLib
ifneq (,$(Sandbox_config))
	@echo "==== Building Sandbox ($(Sandbox_config)) ===="
	@${MAKE} --no-print-directory -C Sandbox -f Makefile config=$(Sandbox_config)
endif

clean:
	@${MAKE} --no-print-directory -C NutzLib -f Makefile clean
	@${MAKE} --no-print-directory -C Sandbox -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   NutzLib"
	@echo "   Sandbox"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"